image: docker:latest

stages:
  - build
  - test
#  - deploy

services:
  - docker:dind

before_script:
  # - 'echo $CI_REGISTRY_IMAGE'
  # - 'echo $CI_COMMIT_REF_SLUG'
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN dockerhub.ebi.ac.uk
  - CI_REGISTRY=dockerhub.ebi.ac.uk
  - CI_REGISTRY_IMAGE=$CI_REGISTRY/$CI_PROJECT_PATH

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo $CI_REGISTRY
    - echo $CI_PROJECT_PATH
    - echo $CI_COMMIT_SHORT_SHA
        # - cp container/Dockerfile .
    # - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    # - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/container/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    entrypoint: [""]
  script:
    - qccalculator

#deploy:
#  stage: deploy
#  script:
#  - mkdir -p glxy
#  - id=$(docker create "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"_glxy)
#  - docker cp $id:/tmp/gxml - > glxy/$CI_COMMIT_REF_SLUG.tar
#  - docker rm -v $id
#  artifacts:
#    paths:
#    - glxy/$CI_COMMIT_REF_SLUG.tar
#  only:
#  - master
